### ISSUE TITLE
Plugin crashes with -PbenchmarkRemoteCache argument

### ISSUE THREAD

**Issue by gzuccarelli** [runningcode/gradle-doctor#239]
Running version **0.7.3** on a gradle 5.6.4 project

When adding `-PbenchmarkRemoteCache` arg,  after executing the build it fails to generate the report
Remote cache is enabled and local disabled. I have also tried enabling the local cache.

```
java.lang.NoSuchMethodError: 'org.gradle.caching.configuration.internal.BuildCacheConfigurationInternal org.gradle.api.internal.SettingsInternal.getBuildCache()'
        at com.osacky.doctor.RemoteCacheEstimation.gradleLocalCacheDir(RemoteCacheEstimation.kt:111)
        at com.osacky.doctor.RemoteCacheEstimation.onFinish(RemoteCacheEstimation.kt:57)
        at com.osacky.doctor.DoctorPlugin$registerBuildFinishActions$runnable$1.run(DoctorPlugin.kt:140)
        at com.osacky.doctor.DoctorPlugin$registerBuildFinishActions$2.execute(DoctorPlugin.kt:161)
        at com.osacky.doctor.DoctorPlugin$registerBuildFinishActions$2.execute(DoctorPlugin.kt:31)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:92)
        at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        ... 79 more

```

**Comment by runningcode** [comment]
Does this work with Gradle 6.0+ ?

**Comment by runningcode** [comment]
Closing due to lack of response. Please feel free to comment back if this is still an issue for you.
